<?php

namespace App\Filament\Admin\Resources\AuditLogResource\Pages;

use App\Filament\Admin\Resources\AuditLogResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use pxlrbt\FilamentExcel\Actions\Pages\ExportAction;
use pxlrbt\FilamentExcel\Columns\Column;
use pxlrbt\FilamentExcel\Exports\ExcelExport;
use Illuminate\Database\Eloquent\Builder;

class ListAuditLogs extends ListRecords
{
    protected static string $resource = AuditLogResource::class;

    protected function getHeaderActions(): array
    {
        return [
//            Actions\CreateAction::make(),
            ExportAction::make()->exports([
                ExcelExport::make()
                    ->withColumns([
                        Column::make('user_type')->heading('User Type'),
                        Column::make('user_id')->heading('User ID'),
                        Column::make('event')->heading('Event'),
                        Column::make('auditable_type')->heading('Auditable Type'),
                        Column::make('auditable_id')->heading('Auditable ID'),
                        Column::make('old_values')->heading('Old Values'),
                        Column::make('new_values')->heading('New Values'),
                        Column::make('url')->heading('Url'),
                        Column::make('ip_address')->heading('IP Address'),
                        Column::make('user_agent')->heading('User Agent'),
                        Column::make('tags')->heading('Tags'),
                        Column::make('created_at')->heading('Creation date'),
                        Column::make('updated_at')->heading('Creation date'),
                    ])
                    ->askForFilename()
                    ->askForWriterType()
            ])
        ];
    }
    
    public function getTableQuery(): ?Builder
    {
        return parent::getTableQuery()->latest(); // TODO: Change the autogenerated stub
    }
}
